e_office_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('secretary/', include('secretary.urls'))

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^logout$', views.logout1, name='logout'),

]

secretary/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'secretary'
urlpatterns = [
    url(r'^$', views.dashboard, name='s_dashboard'),
    url(r'^history$', views.FileIndexView.as_view(), name='history'),
    url(r'^login$', views.LoginFormView.as_view(), name='login'),
    url(r'^upload$', views.FileCreate.as_view(), name='upload'),
    # url(r'^(?P<file_id>[0-9]+)/$', views.append_file_no, name='append_file_no'),
    url(r'^(?P<pk>[0-9]+)/$', views.FileDetailView.as_view(), name='detail'),
    path('append/<int:file_id>/', views.append_file_no, name="append_file_no"),
    path('<int:file_id>/<int:user_id>/', views.comment, name="comment")
]

home/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    secretary = models.BooleanField(default=False)
    ssg = models.BooleanField(default=False)
    perm_sec_political = models.BooleanField(default=False)
    perm_sec = models.BooleanField(default=False)


class File(models.Model):
    file_name = models.CharField(max_length=1000)
    file_number = models.CharField(max_length=100, null=True, blank=True, default=None)
    file = models.FileField()
    date_of_file = models.DateField(null=True, blank=True, default=None)
    comment_from_secretary = models.TextField(max_length=1000, null=True, default=None, blank=True)
    comment_from_ssg = models.TextField(max_length=1000, null=True, default=None, blank=True)
    moved_by_ssg = models.BooleanField(default=False)
    comment_from_perm_sec1 = models.TextField(max_length=1000, null=True, default=None, blank=True)
    moved_by_perm_sec1 = models.BooleanField(default=False)
    comment_from_perm_sec2 = models.TextField(max_length=1000, null=True, default=None, blank=True)
    moved_by_perm_sec2 = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('secretary:append_file_no', kwargs={'file_id': self.pk})

    def __str__(self):
        return self.file_name
# emmamech121@gmail.com

secretary/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

ssg/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import File


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


"""class UploadForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ['file_name', 'file', 'comment_by_secretary']"""

home/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import LoginForm
from .models import *


# Create your views here.
def index(request):
    return render(request, 'home/index.html')


def logout1(request):
    logout(request)
    return HttpResponseRedirect(reverse('home:index'))

secretary/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from home.forms import LoginForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.views.generic.edit import CreateView
from home.models import File
from django.views import generic
from django.forms.widgets import SelectDateWidget
from django.contrib.auth.models import User


# Create your views here.

def dashboard(request):
    n = 0
    m = 0
    j = 0
    try:
        all_files = File.objects.all()
        for file in all_files:
            if not file.moved_by_ssg:
                n += 1
    except File.DoesNotExit:
        n = 0
    try:
        all_files = File.objects.all()
        for file in all_files:
            if not file.moved_by_perm_sec1 and file.moved_by_ssg:
                m += 1
    except File.DoesNotExit:
        m = 0
    try:
        all_files = File.objects.all()
        for file in all_files:
            if not file.moved_by_perm_sec2 and file.moved_by_ssg and file.moved_by_perm_sec1:
                j += 1
    except File.DoesNotExit:
        j = 0
    context = {'no_of_unread': n, 'perm_sec1_unread': m, 'perm_sec2_unread': j}
    return render(request, 'secretary/s_dashboard.html', context)


class FileIndexView(generic.ListView):
    template_name = 'secretary/history.html'
    context_object_name = 'all_files'

    def get_queryset(self):
        return File.objects.all()


class FileDetailView(generic.DetailView):
    model = File
    template_name = 'home/detail.html'


def s_dashboard(request):
    return render(request, 'secretary/s_dashboard.html')


def upload(request):
    return render(request, "secretary/upload.html")

def comment(request, file_id, user_id):
    if request.method == 'POST':
        user = User.objects.get(pk=user_id)
        file = File.objects.get(pk=file_id)
        comment1 = request.POST['comment']
        print(comment1, user.profile.perm_sec_political)
        if user.profile.ssg:
            file.comment_from_ssg = comment1
            file.moved_by_ssg = True
            file.save()
        elif user.profile.perm_sec:
            file.comment_from_perm_sec1 = comment1
            file.moved_by_perm_sec1 = True
            file.save()
        elif user.profile.perm_sec_political:
            print('I am here')
            file.comment_from_perm_sec2 = comment1
            file.moved_by_perm_sec2 = True
            file.save()
        else:
            print('bad')
            return redirect('secretary:s_dashboard')
    return redirect('secretary:s_dashboard')


class LoginFormView(View):
    form_class = LoginForm
    template_name = 'home/login.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(None)
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('secretary:s_dashboard'))
        messages.error(request, 'invalid username or password')
        return render(request, self.template_name, {'form': form})


class FileCreate(CreateView):
    model = File
    fields = ['file_name', 'file', 'date_of_file', 'comment_from_secretary']

    def get_form(self, form_class=None):
        form = super(FileCreate, self).get_form()
        form.fields['date_of_file'].widget = SelectDateWidget()
        return form


def append_file_no(request, file_id):
    file = File.objects.get(pk=int(file_id))
    year = file.date_of_file.strftime('%Y')
    file.file_number = 'ssg/' + str(year) + '/' + str(file_id)
    file.save()
    return redirect('secretary:s_dashboard')

ssg/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from home.forms import LoginForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.views.generic.edit import CreateView
from home.models import File
from django.views import generic

# Create your views here.
class FileIndexView(generic.ListView):
    template_name = 'ssg/s_dashboard.html'
    context_object_name = 'all_files'

    def get_queryset(self):
        return File.objects.all()

home/templates/home/detail.html
{% extends 'home/base.html' %}
    {% block body %}
        <br/>
        {% if user.is_authenticated %}

                    <table>
                        <tr>
                        <th>File Details</th>
                        </tr>

                        <tr>
                            <td>File Name </td>
                            <td>{{ file.file_name }}</td>
                        </tr>

                        <tr>
                            <td>File Number</td>
                            <td>{{ file.file_number }}</td>
                        </tr>
                        <tr>
                            <td>File Date</td>
                            <td>{{file.date_of_file}}</td>
                        </tr>
                        <tr>
                            <td>Secretary's Comment:</td>
                            <td>{{ file.comment_from_secretary }}</td>
                        </tr>
                        {% if not user.profile.secretary %}
                        <tr>
                            <td>SSG's Comment:</td>
                            <td>{{ file.comment_from_ssg }}</td>
                        </tr>
                        <tr>
                            <td>Perm. Sec's Comment:</td>
                            <td>{{ file.comment_from_perm_sec1 }}</td>
                        </tr>
                        {% endif %}
                    </table>
                    <img src="{{ file.file.url }}" style="width:50%;"><br>
<!-- comment box for ssg -->
    {% if user.profile.ssg %}
        {% if not file.moved_by_ssg %}
            <form method="post" action="{% url 'secretary:comment' file.id user.id %}" enctype="multipart/form-data" id="commentform">
            {% csrf_token %}
            <textarea name="comment" form="commentform" placeholder="Enter comment" style="height:200px; width:200px"></textarea><br><br>
            <input type="submit" value="Move File">
        </form>
        {% endif %}
    {% endif %}
<!-- comment box for perm sec1 -->
    {% if user.profile.perm_sec %}
        {% if not file.moved_by_perm_sec1 %}
            <form method="post" action="{% url 'secretary:comment' file.id user.id %}" enctype="multipart/form-data" id="commentform1">
            {% csrf_token %}
            <textarea name="comment" form="commentform1" placeholder="Enter comment" style="height:200px; width:200px"></textarea><br><br>
            <input type="submit" value="Move File">
        </form>
        {% endif %}
    {% endif %}
<!-- comment box for perm sec2 -->
    {% if user.profile.perm_sec_political %}
        {% if file.moved_by_ssg  and file.moved_by_perm_sec1%}
        {% if not file.moved_by_perm_sec2 %}
            <form method="post" action="{% url 'secretary:comment' file.id user.id %}" enctype="multipart/form-data" id="commentform2">
            {% csrf_token %}
            <textarea name="comment" form="commentform2" placeholder="Enter comment" style="height:200px; width:200px"></textarea><br><br>
            <input type="submit" value="Move File">
        </form>
        {% endif %}
        {% endif %}
    {% endif %}
    {% if not user.profile.secretary %}
    <div class="list">

                        <a href="{% url 'secretary:s_dashboard' %}" class="alist">
                            <div class="slist">
                            <span>Dashboard</span>
                            </div>
                        </a>

                        <a href="{% url 'home:logout' %}" class="alist">
                            <div class="slist">
                            <span>Logout</span>
                            </div>
                        </a>
                    </div>
    {% endif %}
    {% if user.profile.secretary %}
        <div class="list">

                        <a href="{% url 'secretary:upload' %}" class="alist">
                            <div class="slist">
                            <span>Register File</span>
                            </div>
                        </a>

                        <a href="{% url 'secretary:s_dashboard' %}" class="alist">
                            <div class="slist">
                            <span>Dashboard</span>
                            </div>
                        </a>

                        <a href="{% url 'home:logout' %}" class="alist">
                            <div class="slist">
                            <span>Logout</span>
                            </div>
                        </a>
                    </div>
    {% endif %}
<!--{% if not file.moved_to_perm_sec1 %}
{% endif %}-->
{% endif %}
    {% endblock %}

home/templates/home/form-template.html
<div >
    {% for field in form %}
<div>{{ field.errors }}</div>
    <label style="width:100px; display:inline; padding: 10px 45px 20px 0; margin: 10px">
        {{ field.label_tag }}
    </label><br>
    {{ field }}<br><br>
    {% endfor %}
</div>

home/templates/home/index.html
{% extends 'home/base.html' %}
    {% block body %}
 <br/>
{% if user.is_authenticated %}
    <div align="center">
            <h3>
            Welcome {{ user.first_name }} {{ user.last_name }}
            </h3>
        </div>
{% endif %}


<div class="list">
    {% if user.is_authenticated %}
    {% if not user.profile.secretary %}
        <a href="{% url 'secretary:history' %}" class="alist">
                        <div class="slist">
                        <span>Unmoved File <button style="background:red; color:white; border:0px; border-radius: 10px;">{{perm_sec2_unread}}</button></span>
                        </div>
                    </a>

        <a href="{% url 'secretary:history' %}" class="alist">
                        <div class="slist">
                        <span>History</span>
                        </div>
                    </a>

        <a href="{% url 'home:logout' %}" class="alist">
                        <div class="slist">
                        <span>Logout</span>
                        </div>
                    </a>
        {% else %}
          <div class="list">

                    <a href="{% url 'secretary:upload' %}" class="alist">
                        <div class="slist">
                        <span>Register File</span>
                        </div>
                    </a>

                    <a href="{% url 'secretary:history' %}" class="alist">
                        <div class="slist">
                        <span>History</span>
                        </div>
                    </a>

                    <a href="{% url 'home:logout' %}" class="alist">
                        <div class="slist">
                        <span>Logout</span>
                        </div>
                    </a>
                </div>
        {% endif %}

    <!--
    <a href="#" class="alist">
        <div class="slist">

        <span>SSG<br>Login</span>
    </div>
    </a>
    <a href="#" class="alist">
        <div class="slist">
        <span>Perm. Sec.<br>Login</span>
    </div>
    </a>
    <a href="#" class="alist">
    <div class="slist">
    <span>Perm. Sec. (Political)<br>Login</span>
    </div>
    </a>
    -->
    {% else %}
    <a href="{% url 'secretary:login' %}" class="alist">
        <div class="slist">
        <span>Login</span>
        </div>
    </a>
    {% endif %}
</div>
    {% endblock %}

secretary/templates/secretary/history.html
{% extends 'home/base.html' %}

    {% block body %}
 <br/>
        {% if user.is_authenticated %}

            <div align="center">
            <h3>
            Welcome {{ user.first_name }} {{ user.last_name }}
            </h3>
            </div>


<!-- Secretary's moved File -->
                {% if user.profile.secretary %}

                <div class="list">
                    <span>File History</span>
                </div><br>
                <div class="list" style="background:white; color:black;">

                    {% if all_files %}
                    <table>
                        <tr>
                        <th>File_Name</th>
                        <th>File Date</th>
                        <th>File Number</th>
                        </tr>
                        {% for file in all_files %}
                        <tr>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file}}</a></td>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file.date_of_file}}</a></td>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file.file_number}}</a></td>
                        </tr>
                        {% endfor %}
                    </table>
                    {% else %}
                    <p>No file available</p>
                    {% endif %}
                </div><br>

                <div class="list">

                    <a href="{% url 'secretary:upload' %}" class="alist">
                        <div class="slist">
                        <span>Register File</span>
                        </div>
                    </a>

                    <a href="{% url 'secretary:s_dashboard' %}" class="alist">
                        <div class="slist">
                        <span>Dashboard</span>
                        </div>
                    </a>

                    <a href="{% url 'home:logout' %}" class="alist">
                        <div class="slist">
                        <span>Logout</span>
                        </div>
                    </a>
                </div>
                {% endif %}
<!-- SSG's Unmoved File -->

                {% if user.profile.ssg %}

                <div class="list">
                    <span>Unmoved File History</span>
                </div><br>
                <div class="list" style="background:white; color:black;">

                    {% if all_files %}
                    <table>
                        <tr>
                        <th>File_Name</th>
                        <th>File Date</th>
                        <th>File Number</th>
                        </tr>
                        {% for file in all_files %}
                        {% if not file.moved_by_ssg %}
                        <tr>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file}}</a></td>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file.date_of_file}}</a></td>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file.file_number}}</a></td>
                        </tr>
                        {% endif %}
                        {% endfor %}

                    </table>
                    {% else %}
                    <p>No file available</p>
                    {% endif %}
                </div><br>
<!-- moved files -->
                <div class="list">
                    <span>Moved File History</span>
                </div><br>

                <div class="list" style="background:white; color:black;">

                    {% if all_files %}
                    <table>
                        <tr>
                        <th>File_Name</th>
                        <th>File Date</th>
                        <th>File Number</th>
                        </tr>
                        {% for file in all_files %}
                        {% if file.moved_by_ssg %}
                        <tr>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file}}</a></td>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file.date_of_file}}</a></td>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file.file_number}}</a></td>
                        </tr>
                        {% endif %}
                        {% endfor %}

                    </table>
                    {% else %}
                    <p>No file available</p>
                    {% endif %}
                </div><br>

                {% endif %}
<!-- Permsec1's Unmoved File -->

                {% if user.profile.perm_sec %}

                <div class="list">
                    <span>Unmoved File History</span>
                </div><br>
                <div class="list" style="background:white; color:black;">

                    {% if all_files %}
                    <table>
                        <tr>
                        <th>File_Name</th>
                        <th>File Date</th>
                        <th>File Number</th>
                        </tr>
                        {% for file in all_files %}
                        {% if not file.moved_by_perm_sec1 %}
                            {% if file.moved_by_ssg %}
                        <tr>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file}}</a></td>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file.date_of_file}}</a></td>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file.file_number}}</a></td>
                        </tr>
                            {% endif %}
                        {% endif %}
                        {% endfor %}

                    </table>
                    {% else %}
                    <p>No file available</p>
                    {% endif %}
                </div><br>
<!-- moved files -->
                <div class="list">
                    <span>Moved File History</span>
                </div><br>

                <div class="list" style="background:white; color:black;">

                    {% if all_files %}
                    <table>
                        <tr>
                        <th>File_Name</th>
                        <th>File Date</th>
                        <th>File Number</th>
                        </tr>
                        {% for file in all_files %}
                        {% if file.moved_by_perm_sec1 %}
                            {% if file.moved_by_ssg %}
                        <tr>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file}}</a></td>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file.date_of_file}}</a></td>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file.file_number}}</a></td>
                        </tr>
                            {% endif %}
                        {% endif %}
                        {% endfor %}

                    </table>
                    {% else %}
                    <p>No file available</p>
                    {% endif %}
                </div><br>


                {% endif %}
<!-- Permsec2's Unmoved File -->

                {% if user.profile.perm_sec_political %}

                <div class="list">
                    <span>Unmoved File History</span>
                </div><br>
                <div class="list" style="background:white; color:black;">

                    {% if all_files %}
                    <table>
                        <tr>
                        <th>File_Name</th>
                        <th>File Date</th>
                        <th>File Number</th>
                        </tr>
                        {% for file in all_files %}
                        {% if not file.moved_by_perm_sec2 %}
                            {% if file.moved_by_ssg  and file.moved_by_perm_sec1%}
                        <tr>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file}}</a></td>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file.date_of_file}}</a></td>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file.file_number}}</a></td>
                        </tr>
                            {% endif %}
                        {% endif %}
                        {% endfor %}

                    </table>
                    {% else %}
                    <p>No file available</p>
                    {% endif %}
                </div><br>
<!-- moved files -->
                <div class="list">
                    <span>Moved File History</span>
                </div><br>

                <div class="list" style="background:white; color:black;">

                    {% if all_files %}
                    <table>
                        <tr>
                        <th>File_Name</th>
                        <th>File Date</th>
                        <th>File Number</th>
                        </tr>
                        {% for file in all_files %}
                        {% if file.moved_by_perm_sec2 %}
                            {% if file.moved_by_ssg  and file.moved_by_perm_sec1%}
                        <tr>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file}}</a></td>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file.date_of_file}}</a></td>
                            <td><a href="{% url 'secretary:detail' file.id %}">{{file.file_number}}</a></td>
                        </tr>
                            {% endif %}
                        {% endif %}
                        {% endfor %}

                    </table>
                    {% else %}
                    <p>No file available</p>
                    {% endif %}
                </div><br>


                {% endif %}
    {% if not user.profile.secretary %}
    <div class="list">

                        <a href="{% url 'secretary:s_dashboard' %}" class="alist">
                            <div class="slist">
                            <span>Dashboard</span>
                            </div>
                        </a>

                        <a href="{% url 'home:logout' %}" class="alist">
                            <div class="slist">
                            <span>Logout</span>
                            </div>
                        </a>
                    </div>
    {% endif %}
{% endif %}


    {% endblock %}

secretary/templates/secretary/s_dashboard.html
{% extends 'home/base.html' %}

 <!-- {% block login %}
          <div align="right" style="display: inline-block;">
                <a href="{% url 'secretary:login' %}" class="login"><button class="button"> <span class="strong">Login</span></button> </a>
            </div>
{% endblock %} -->
    {% block body %}
 <br/>
        {% if user.is_authenticated %}

            <div align="center">
            <h3>
            Welcome {{ user.first_name }} {{ user.last_name }}
            </h3>
            </div>
<!-- secretary's Dashboard -->

                {% if user.profile.secretary %}
                    <div class="list">

                    <a href="{% url 'secretary:upload' %}" class="alist">
                        <div class="slist">
                        <span>Register File</span>
                        </div>
                    </a>

                    <a href="{% url 'secretary:history' %}" class="alist">
                        <div class="slist">
                        <span>History</span>
                        </div>
                    </a>

                    <a href="{% url 'home:logout' %}" class="alist">
                        <div class="slist">
                        <span>Logout</span>
                        </div>
                    </a>
                </div>

                {% endif %}
<!-- ssg's Dashboard -->
<div class="list">

                {% if user.profile.ssg %}

                    <a href="{% url 'secretary:history' %}" class="alist">
                        <div class="slist">
                        <span>Unmoved File <button style="background:red; color:white; border:0px; border-radius: 10px;">{{no_of_unread}}</button></span>
                        </div>
                    </a>

                    <a href="{% url 'secretary:history' %}" class="alist">
                        <div class="slist">
                        <span>History</span>
                        </div>
                    </a>

                    <a href="{% url 'home:logout' %}" class="alist">
                        <div class="slist">
                        <span>Logout</span>
                        </div>
                    </a>

                {% endif %}
</div>
<!-- perm sec1's Dashboard -->
                {% if user.profile.perm_sec %}
<div class="list">
                    <a href="{% url 'secretary:history' %}" class="alist">
                        <div class="slist">
                        <span>Unmoved File <button style="background:red; color:white; border:0px; border-radius: 10px;">{{perm_sec1_unread}}</button></span>
                        </div>
                    </a>

                    <a href="{% url 'secretary:history' %}" class="alist">
                        <div class="slist">
                        <span>History</span>
                        </div>
                    </a>

                    <a href="{% url 'home:logout' %}" class="alist">
                        <div class="slist">
                        <span>Logout</span>
                        </div>
                    </a>

</div>
            {% endif %}
<!-- perm sec1's Dashboard -->

                {% if user.profile.perm_sec_political %}
<div class="list">
                    <a href="{% url 'secretary:history' %}" class="alist">
                        <div class="slist">
                        <span>Unmoved File <button style="background:red; color:white; border:0px; border-radius: 10px;">{{perm_sec2_unread}}</button></span>
                        </div>
                    </a>

                    <a href="{% url 'secretary:history' %}" class="alist">
                        <div class="slist">
                        <span>History</span>
                        </div>
                    </a>

                    <a href="{% url 'home:logout' %}" class="alist">
                        <div class="slist">
                        <span>Logout</span>
                        </div>
                    </a>
</div>
                {% endif %}

{% endif %}
    {% endblock %}

ssg/templates/ssg/s_dashboard.html
{% extends 'home/base.html' %}

 <!-- {% block login %}
          <div align="right" style="display: inline-block;">
                <a href="{% url 'secretary:login' %}" class="login"><button class="button"> <span class="strong">Login</span></button> </a>
            </div>
{% endblock %} -->
    {% block body %}
 <br/>
        {% if user.is_authenticated %}
            <div align="center">
            <h3>
            Welcome {{ user.first_name }} {{ user.last_name }}
            </h3>
        </div>
        {% endif %}
<div class="list">
    <a href="{% url 'ssg:comment' %}" class="alist">
        <div class="slist">
        <span>unmoved File</span>
    </div>
    </a>

    <a href="#" class="alist">
        <div class="slist">

        <span>History</span>
    </div>
    </a>

    <a href="#" class="alist">
    <div class="slist">
    <span>Logout</span>
    </div>
    </a>
</div><br>
<div class="list">
    <span>File History</span>
</div><br>
<ul>
    {% for file in all_files %}
    <li><a href="{% url 'secretary:detail' file.id %}">{{file}}</a></li>
    {% endfor %}
</ul>
    {% endblock %}